### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by yichen88**

### CODE REVIEW

**Comment by bupticybee** [comment]
I see the point of this merge requets. However the .idea folder is added on purpose. I use some of Intellij IDEA's feature to buid the release package and manage the test cases.

**Comment by yichen88** [comment]
> I see the point of this merge requets. However the .idea folder is added on purpose. I use some of Intellij IDEA's feature to buid the release package and manage the test cases. It's an important part of the project.

ok, normally these jobs(test, release) could be done by maven plugins. i will try it.

**Comment by bupticybee** [comment]
> > I see the point of this merge requets. However the .idea folder is added on purpose. I use some of Intellij IDEA's feature to buid the release package and manage the test cases. It's an important part of the project.
> 
> ok, normally these jobs(test, release) could be done by maven plugins. i will try it.

Maven cannot meet my demands so I choose Intellij IDEA embedded build options.

**Comment by bupticybee** [comment]
Closing for now.

**Pull request closed without merging**
